### ISSUE TITLE
Handle keyboard interrupt gracefully

### ISSUE THREAD

**Issue by gituser12981u2** [gituser12981u2/audio_visualizer#20]
**Is your feature request related to a problem? Please describe.**
When the visualization is stopped with a keyboard interrupt it prints the logging and ^C and the visualizer is frozen in place.

**Describe the solution you'd like**
When a keyboard interrupt is triggered ^C shouldn't be printed and the terminal should be cleaned of the visualizer. A simple message should be displayed.

**Additional context**
<img width="679" alt="image" src="https://github.com/gituser12981u2/audio_visualizer/assets/119834691/ad6ce71f-57b6-4d12-9569-ea8129281037">

**Comment by ohksith** [comment]
Pull request initiated
